import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header1 from "../components/header1";
import Home1 from "../components/home1";
import Home2 from "../components/home2";

const Home: NextPage = () => {
  return (
    <div className="bgcolor w-full min-h-screen">
      <Head>
        <title>The End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header1 />
      <Home1 />
    </div>
  );
};

export default Home;
