/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import { getPopularFilms } from "../utils/apis";
import Landing from "../components/landing";
import Link from "next/link";
import { StarIcon } from "@heroicons/react/20/solid";
import { classNames } from "../constants";
import { useDispatch } from "react-redux";
import { useEffect, useState } from "react";
import { useAppSelector } from "../redux/app/hookes";
import { generateNumber } from "../utils/functions";

const Home: NextPage = () => {
  const films = useAppSelector((state) => state.filmsSlice.popularFilms);
  const [pageNo, setPageNo] = useState(generateNumber());
  const [imageUrl, setImageUrl] = useState();

  const dispatch = useDispatch();
  const updatePopularFilms = async () => {
    await getPopularFilms(dispatch, pageNo, setImageUrl);
  };

  useEffect(() => {
    updatePopularFilms();
  }, [pageNo]);
  return (
    <div className="bgcolor w-full min-h-screen">
      <Head>
        <title>The End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="bg"
        style={{
          backgroundImage: `url(${imageUrl})`,
        }}
      >
        <Landing />
        <div className="bgcolor">
          <div className="mx-auto max-w-7xl overflow-hidden sm:px-6 lg:px-8">
            <h3 className="text-gray-500 pb-3 pt-10">Popular Films</h3>
            <h2 className="sr-only">films</h2>

            <div className="-mx-px grid grid-cols-2 sm:mx-0 md:grid-cols-3 lg:grid-cols-4">
              {films.map((film) => (
                <Link key={film.id} href={`/films/${film.id}`}>
                  <div className="group relative  p-4 sm:p-6 cursor-pointer">
                    <div className="aspect-w-1 aspect-h-1 overflow-hidden rounded-lg bg-gray-200 group-hover:opacity-75">
                      <img
                        src={`https://image.tmdb.org/t/p/w780/${film.poster_path}`}
                        alt="NoPhoto"
                        className="h-full w-full"
                      />
                    </div>
                    <div className="pt-10 pb-4 text-center">
                      <h3 className="text-sm font-medium text-gray-900">
                        <a className="hover:text-white">
                          <span
                            aria-hidden="true"
                            className="absolute inset-0"
                          />
                          {film.title}
                        </a>
                      </h3>
                      <div className="mt-3 flex flex-col items-center">
                        <p className="sr-only">
                          {film.vote_average} out of 5 stars
                        </p>
                        <div className="flex items-center">
                          {[0, 1, 2, 3, 4].map((rating) => (
                            <StarIcon
                              key={rating}
                              className={classNames(
                                film.vote_average > rating
                                  ? "text-yellow-400"
                                  : "text-gray-200",
                                "flex-shrink-0 h-5 w-5"
                              )}
                              aria-hidden="true"
                            />
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
              ))}
            </div>

            <div className="flex justify-between">
              {pageNo > 1 ? (
                <div>
                  <h1
                    className=" text-xl font-bold uppercase txt cursor-pointer"
                    onClick={() => setPageNo(pageNo - 1)}
                  >
                    prev
                  </h1>
                </div>
              ) : null}

              {pageNo < 500 ? (
                <div>
                  <h1
                    className=" text-xl font-bold uppercase txt cursor-pointer"
                    onClick={() => setPageNo(pageNo + 1)}
                  >
                    next
                  </h1>
                </div>
              ) : null}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
